sudo: required

language: java

# required for oraclejdk9
dist: trusty
group: edge

jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk9
      env: MAVEN_SKIP_RC=true
  allow_failures:
    - jdk: oraclejdk9

install:
  - ./gradlew --version
  - mvn --version

script:
  - ./gradlew -Dmaven.repo.local=maven/target/m2 --continue :build :maven:deploy

after_success:
  - git status

cache:
  directories:
    - $HOME/.gradle
