sudo: false
language: java
jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - TERM=dumb

install:
  - ./gradlew --version

script:
  - ./gradlew --continue

after_success:
  - git status

cache:
  directories:
    - cnf/cache/stable
