sudo: false

language: java

jdk:
  - oraclejdk7
  - oraclejdk8

install:
  - ./gradlew --version
  - mvn --version

script:
  - ./gradlew -Dmaven.repo.local=maven/target/m2 --continue :build :maven:deploy

after_success:
  - git status

cache:
  directories:
    - $HOME/.gradle
