sudo: false

language: java

jdk:
  - oraclejdk8

before_install:
  - unset _JAVA_OPTIONS

install:
  - ./gradlew --no-daemon --version

script:
  - ./gradlew --no-daemon -Dmaven.repo.local=cnf/cache/stable/m2 --continue

before_cache:
  - git status
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - cnf/cache/stable/
