sudo: false

language: java

jdk:
  - oraclejdk7
  - oraclejdk8

# required for oraclejdk9
#sudo: required
#dist: trusty
#group: edge
#
#matrix:
#  fast_finish: true
#  include:
#    - jdk: oraclejdk9
#      env: MAVEN_SKIP_RC=true
#  allow_failures:
#    - jdk: oraclejdk9

before_install:
  - rvm --version
  - rvm install 2.0.0

install:
  - ./gradlew --version
  - ./mvnw --version
  - ruby --version
  - gem --version
  - bundle --version

script:
  - ./gradlew -Dmaven.repo.local=maven/target/m2 --continue :build :maven:deploy
  - (cd docs && ./build.sh)

after_success:
  - git status

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.m2/wrapper
    - cnf/cache/stable
    - docs/bundler
