version: '{build}'

clone_depth: 50

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - gradlew.bat --version
  - mvnw.cmd --version

build_script:
  - gradlew.bat -Dmaven.repo.local=maven/target/m2 --continue :build :maven:deploy

on_success:
  - git status

cache:
  - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties
  - C:\Users\appveyor\.m2\wrapper -> .mvn\wrapper\maven-wrapper.properties
  - cnf\cache\stable
