version: '{build}'

clone_depth: 50

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - gradlew.bat --version
  - choco install maven --version 3.2.5
  - set PATH=%PATH%;C:\bin\apache-maven-3.2.5\bin
  - mvn --version

build_script:
  - gradlew.bat -Dmaven.repo.local=maven/target/m2 --continue
  - mvn -f maven --batch-mode --quiet -Dmaven.repo.local=maven/target/m2 -DaltDeploymentRepository=dist::default::file:dist/bundles/ deploy

on_success:
  - git status

cache:
  - C:\Users\appveyor\.gradle -> .gradle-wrapper\gradle-wrapper.properties
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\bin\apache-maven-3.2.5\ -> appveyor.yml
