name: 'Docs Build'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - 'docs/**'
    - '.github/**/*docs*'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/**/*docs*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  docs:
    name: GitHub Pages
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
      BUNDLE_PATH: vendor/bundle
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Set up Ruby
      uses: ruby/setup-ruby@50ba3386b050ad5b97a41fcb81240cbee1d1821f
      with:
        ruby-version: 2.7
        bundler-cache: true
        working-directory: docs
    - name: Build
      run: |
        ./.github/scripts/docs.sh
