name: 'Docs Build'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - 'docs/**'
    - '.github/**/*docs*'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/**/*docs*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  docs:
    name: GitHub Pages
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
      BUNDLE_PATH: vendor/bundle
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Set up Ruby
      uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854
      with:
        ruby-version: 2.7
        bundler-cache: true
        working-directory: docs
    - name: Build
      run: |
        ./.github/scripts/docs.sh
