name: 'Rebuild'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - '.github/**/*rebuild*'
  pull_request:
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - '.github/**/*rebuild*'

env:
  LC_ALL: en_US.UTF-8
  GRADLE_OPTS: >-
    -Dorg.gradle.parallel=true
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryHandler.count=3
    -Daether.connector.http.retryHandler.count=5
    -Daether.connector.http.reuseConnections=false
    -Daether.connector.http.connectionMaxTtl=25
    -Daether.connector.connectTimeout=120000

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: ${{ (github.repository != 'bndtools/bnd') || ((github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/next')) || (github.event_name == 'pull_request') }}
      matrix:
        os:
        - 'ubuntu-latest'
        java:
        - '17'
    name: Build JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    outputs:
      dist-bundles: Dist_Bundles_JDK${{ matrix.java }}_${{ matrix.os }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Set up Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
    - name: Build
      id: build
      run: |
        ./.github/scripts/rebuild-build.sh
    - name: Upload dist/bundles
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: Dist_Bundles_JDK${{ matrix.java }}_${{ matrix.os }}
        if-no-files-found: error
        path: dist/bundles/

  rebuild:
    needs: build
    strategy:
      fail-fast: ${{ (github.repository != 'bndtools/bnd') || ((github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/next')) || (github.event_name == 'pull_request') }}
      matrix:
        os:
        - 'ubuntu-latest'
        java:
        - '17'
        - '19'
        runner:
        - 'xvfb-run --auto-servernum {0}'
    name: Rebuild JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - name: Set up Java
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Set up Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
    - name: Download dist/bundles
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: ${{ needs.build.outputs.dist-bundles }}
        path: dist/bundles
    - name: Rebuild
      id: build
      run: |
        ${{ format(matrix.runner, './.github/scripts/rebuild-test.sh') }}
    - name: Upload Test Reports
      if: ${{ always() && ((steps.build.outcome == 'success') || (steps.build.outcome == 'failure')) }}
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: Rebuild_JDK${{ matrix.java }}_${{ matrix.os }}-test-reports
        path: |
          */generated/test-reports/*/TEST-*.xml
          maven/*/target/surefire-reports/TEST-*.xml
          gradle-plugins/*/build/test-results/*/TEST-*.xml
