name: 'wip'

#
# Used to debug actions
#


on:
  workflow_dispatch:
    inputs:
      V1:
        description: 'The just released version'
        required: true
        type: string

permissions:
  contents: read

jobs:

  #
  #

  publish-gradle-plugin:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET}}
      GRADLE_PUBLISH_KEY:    ${{ secrets.GRADLE_PUBLISH_KEY}}
    steps:
    - name: set up java
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
      with:
        distribution: 'temurin'
        java-version: |
          17

    - name: Git Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        ref: next

    - name: publish 
      run: |
        mkdir -p ~/.gradle/
        echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >~/.gradle/gradle.properties
        echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >>~/.gradle/gradle.properties
        cd gradle-plugins/biz.aQute.bnd.gradle
        ../gradlew clean
        ../gradlew build
        ../gradlew publishPlugins --validate-only -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
