name: 'wip'

#
# Used to debug actions
#


on:
  workflow_dispatch:
    inputs:
      V1:
        description: 'The just released version'
        required: true
        type: string

permissions:
  contents: read

jobs:

  #
  #

  release-doc-generate:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET}}
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY}}
    steps:
    - name: Git Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: next

    - name: publish 
      run: |
        cd gradle-plugins/biz.aQute.bnd.gradle
        ../gradlew clean
        ../gradlew build
        ../gradlew publishPlugins --validate-only
